import { createElement } from 'lwc';
import ThirtyNineCom_getObjectInfoAdapter from 'c/thirtyNineCom_getObjectInfoAdapter';

describe('c-thirty-nine-com-get-object-info-adapter', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-thirty-nine-com-get-object-info-adapter', {
            is: ThirtyNineCom_getObjectInfoAdapter
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});