import { createElement } from 'lwc';
import FortyTwoCom_getPicklistValuesByRecordTypeAdapter from 'c/fortyTwoCom_getPicklistValuesByRecordTypeAdapter';

describe('c-forty-two-com-get-picklist-values-by-record-type-adapter', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-forty-two-com-get-picklist-values-by-record-type-adapter', {
            is: FortyTwoCom_getPicklistValuesByRecordTypeAdapter
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});