import { createElement } from 'lwc';
import FortyCom_getObjectInfosAdapter from 'c/fortyCom_getObjectInfosAdapter';

describe('c-forty-com-get-object-infos-adapter', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-forty-com-get-object-infos-adapter', {
            is: FortyCom_getObjectInfosAdapter
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});