import { createElement } from 'lwc';
import FiftyCom_Apex_Method_Using_Wire from 'c/fiftyCom_Apex_Method_Using_Wire';

describe('c-fifty-com-apex-method-using-wire', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-fifty-com-apex-method-using-wire', {
            is: FiftyCom_Apex_Method_Using_Wire
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});