import { createElement } from 'lwc';
import TwentyOneCom_ReusableComp from 'c/twentyOneCom_ReusableComp';

describe('c-twenty-one-com-reusable-comp', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-twenty-one-com-reusable-comp', {
            is: TwentyOneCom_ReusableComp
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});