import { createElement } from 'lwc';
import TwentyFiveCom_thirdParty_JS_Library from 'c/twentyFiveCom_thirdParty_JS_Library';

describe('c-twenty-five-com-third-party-j-s-library', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-twenty-five-com-third-party-j-s-library', {
            is: TwentyFiveCom_thirdParty_JS_Library
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});