import { createElement } from 'lwc';
import TwentyTwoCom_LMS_Publisher from 'c/twentyTwoCom_LMS_Publisher';

describe('c-twenty-two-com-l-m-s-publisher', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-twenty-two-com-l-m-s-publisher', {
            is: TwentyTwoCom_LMS_Publisher
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});