import { createElement } from 'lwc';
import FourteenCom_ParentToChildComm_Child3 from 'c/fourteenCom_ParentToChildComm_Child3';

describe('c-fourteen-com-parent-to-child-comm-child3', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-fourteen-com-parent-to-child-comm-child3', {
            is: FourteenCom_ParentToChildComm_Child3
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});