import { createElement } from 'lwc';
import NinthCom_SharedCssComponent from 'c/ninthCom_SharedCssComponent';

describe('c-ninth-com-shared-css-component', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-ninth-com-shared-css-component', {
            is: NinthCom_SharedCssComponent
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});