import { createElement } from 'lwc';
import FortyFiveCom_getNavItemsAdapter from 'c/fortyFiveCom_getNavItemsAdapter';

describe('c-forty-five-com-get-nav-items-adapter', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-forty-five-com-get-nav-items-adapter', {
            is: FortyFiveCom_getNavItemsAdapter
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});