import { createElement } from 'lwc';
import FiftyOneCom_Apex_Method_With_Parameter from 'c/fiftyOneCom_Apex_Method_With_Parameter';

describe('c-fifty-one-com-apex-method-with-parameter', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-fifty-one-com-apex-method-with-parameter', {
            is: FiftyOneCom_Apex_Method_With_Parameter
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});