import { createElement } from 'lwc';
import TwentyFourCom_Image_StaticResource from 'c/twentyFourCom_Image_StaticResource';

describe('c-twenty-four-com-image-static-resource', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-twenty-four-com-image-static-resource', {
            is: TwentyFourCom_Image_StaticResource
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});