import { createElement } from 'lwc';
import FortyNineCom_deleteRecordAdapter from 'c/fortyNineCom_deleteRecordAdapter';

describe('c-forty-nine-com-delete-record-adapter', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-forty-nine-com-delete-record-adapter', {
            is: FortyNineCom_deleteRecordAdapter
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});