import { createElement } from 'lwc';
import ThirtyEightCom_WireAdapterService from 'c/thirtyEightCom_WireAdapterService';

describe('c-thirty-eight-com-wire-adapter-service', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-thirty-eight-com-wire-adapter-service', {
            is: ThirtyEightCom_WireAdapterService
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});