import { createElement } from 'lwc';
import FortyEightCom_updateRecordAdapter from 'c/fortyEightCom_updateRecordAdapter';

describe('c-forty-eight-com-update-record-adapter', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-forty-eight-com-update-record-adapter', {
            is: FortyEightCom_updateRecordAdapter
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});