import { createElement } from 'lwc';
import FortyThreeCom_getRecordAdapter from 'c/fortyThreeCom_getRecordAdapter';

describe('c-forty-three-com-get-record-adapter', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-forty-three-com-get-record-adapter', {
            is: FortyThreeCom_getRecordAdapter
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});